"use client";

import { useState, useTransition, useRef, useEffect } from "react";
import Link from "next/link";
import {
  Calendar,
  Wand2,
  Pencil,
  Trash2,
  MoreVertical,
  Square,
  Sparkles,
  Copy,
  Radio,
  Archive,
  Plus,
  Play,
  ClipboardCheck,
  LogIn,
  Images,
  CalendarClock,
} from "lucide-react";
import { motion } from "framer-motion";
import { SessionWizardModal } from "@/src/components/dashboard/SessionWizardModal";
import { CampaignEventModal } from "@/src/components/dashboard/CampaignEventModal";
import { SessionEditModal } from "@/src/components/dashboard/SessionEditModal";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  deleteSession,
  cancelSession,
  markSessionPlanningComplete,
  archiveScheduledSessionQuietly,
  setPlanningDummyPlayerCount,
} from "./session-actions";
import { StartSessionBackgroundModal } from "@/src/components/dashboard/StartSessionBackgroundModal";
import { SessionChronistModeControl } from "@/src/components/session/SessionChronistModeControl";
import { SessionEndWrapUpModal } from "@/src/components/session/SessionEndWrapUpModal";
import type { TranscriptionMode } from "@/src/lib/session-chronicle/constants";
import {
  PastSessionsGallery,
  type SessionArchiveItem,
} from "@/src/components/dashboard/campaigns/PastSessionsGallery";
import { LastSessionRecapCard } from "@/src/components/chronicle/LastSessionRecapCard";
import type { LatestPublishedPlayerRecap } from "@/src/lib/session-chronicle/latest-published-recap";
import {
  isSessionStatusLive,
  isSessionStatusScheduled,
  isSessionStatusTerminal,
  canEditSessionSchedule,
} from "@/src/lib/session-status";
import {
  isMissedScheduledSession,
  isScheduledInGraceOverdue,
  isStaleLiveSession,
  SCHEDULED_NOT_STARTED_GRACE_HOURS,
} from "@/src/lib/session-focus";
import { getSessionTypeLabel, sessionSupportsLiveBoard } from "@/src/lib/session-type";

type SessionItem = {
  id: string;
  title: string | null;
  start_time: string;
  end_time?: string | null;
  type: string;
  status: string;
  canStart?: boolean;
  pendingCount?: number;
  hasAcceptedRsvps?: boolean;
  gm_prep_complete?: boolean;
  registration_closed_on_landing?: boolean | null;
  /** Aus session_live_states — Platzhalter am Tisch (0–3) */
  planning_dummy_player_count?: number;
  transcription_mode?: string | null;
};

function parseTranscriptionMode(value: unknown): TranscriptionMode | null {
  if (value === "table" || value === "jitsi") return value;
  return null;
}

import { formatSessionDateTimeDe } from "@/src/lib/datetime/berlin";

function formatSessionDateTime(startTime: string) {
  const { formattedDate, formattedTime } = formatSessionDateTimeDe(startTime);
  const startDate = new Date(startTime);
  return { formattedDate, formattedTime, startDate };
}

function pastSessionStatusLabel(session: SessionItem): string {
  if (isMissedScheduledSession(session)) {
    return "Nicht gestartet (Toleranz abgelaufen)";
  }
  const st = String(session.status ?? "").toLowerCase();
  if (st === "cancelled") return "Abgesagt";
  if (st === "completed") return "Beendet / archiviert";
  if (isSessionStatusLive(session.status)) return "Verwaiste Live-Session";
  return session.status;
}

function isAutoGeneratedSessionTitle(title: string | null | undefined): boolean {
  if (!title?.trim()) return true;
  return /^Session\s*[–-]\s*/.test(title.trim());
}

const panelActionClass =
  "inline-flex w-full items-center justify-center gap-2 rounded-lg border border-hero-border/40 bg-background-dark px-4 py-2.5 font-barlow text-xs font-bold uppercase tracking-wide text-gray-100 transition-colors hover:border-white/35 hover:bg-hero-dark disabled:cursor-not-allowed disabled:opacity-50";

function sessionCardBorderClass(session: SessionItem): string {
  const live = isSessionStatusLive(session.status);
  const scheduled = isSessionStatusScheduled(session.status);
  if (live) return "border-red-800/50";
  if (scheduled && isScheduledInGraceOverdue(session)) {
    return "border-amber-600/50 ring-1 ring-amber-900/40";
  }
  if (scheduled) return "border-emerald-800/40";
  return "border-hero-border/30";
}

/** Dropdown mit Bearbeiten/Löschen/Absagen/Archivieren/Beenden für GM */
function SessionActionsDropdown({
  isStarting,
  onEdit,
  onEditSchedule,
  onDelete,
  onCancel,
  onArchiveQuiet,
  onEnd,
  hasAcceptedRsvps,
  isLive,
  isScheduled,
  canEditSchedule,
  allowDelete = false,
}: {
  isStarting: boolean;
  onEdit?: () => void;
  onEditSchedule?: () => void;
  onDelete: () => void;
  onCancel?: () => void;
  onArchiveQuiet?: () => void;
  onEnd?: () => void;
  hasAcceptedRsvps?: boolean;
  isLive?: boolean;
  isScheduled?: boolean;
  canEditSchedule?: boolean;
  /** Löschen nur im Archiv-Reiter. */
  allowDelete?: boolean;
}) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    };
    document.addEventListener("click", handleClickOutside);
    return () => document.removeEventListener("click", handleClickOutside);
  }, []);

  return (
    <div className="relative" ref={ref}>
      <button
        type="button"
        onClick={(e) => {
          e.stopPropagation();
          setOpen((o) => !o);
        }}
        className="rounded p-2 text-gray-400 hover:text-white hover:bg-hero-dark transition-colors"
        title="Aktionen"
        aria-label="Session-Aktionen"
      >
        <MoreVertical className="h-4 w-4" />
      </button>
      {open && (
        <div className="absolute right-0 top-full mt-1 z-20 min-w-[140px] rounded border border-hero-dark bg-background-card py-1 shadow-xl">
          {isLive && onEnd ? (
            <button
              type="button"
              onClick={(e) => {
                e.stopPropagation();
                setOpen(false);
                onEnd();
              }}
              disabled={isStarting}
              className="flex w-full items-center gap-2 px-3 py-2 text-left font-barlow text-sm uppercase text-amber-400 hover:bg-amber-900/30 transition-colors disabled:opacity-50"
            >
              <Square className="h-4 w-4" />
              Session beenden
            </button>
          ) : (
            <>
              {canEditSchedule && onEditSchedule ? (
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    setOpen(false);
                    onEditSchedule();
                  }}
                  className="flex w-full items-center gap-2 px-3 py-2 text-left font-barlow text-sm uppercase text-hero-vibrant hover:bg-hero-dark transition-colors"
                >
                  <Calendar className="h-4 w-4" />
                  Termin ändern
                </button>
              ) : onEdit ? (
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    setOpen(false);
                    onEdit();
                  }}
                  className="flex w-full items-center gap-2 px-3 py-2 text-left font-barlow text-sm uppercase text-gray-300 hover:bg-hero-dark hover:text-hero-vibrant transition-colors"
                >
                  <Pencil className="h-4 w-4" />
                  Bearbeiten
                </button>
              ) : null}
              {isScheduled && onCancel ? (
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    setOpen(false);
                    onCancel();
                  }}
                  disabled={isStarting}
                  className="flex w-full items-center gap-2 px-3 py-2 text-left font-barlow text-sm uppercase text-amber-400 hover:bg-amber-900/30 transition-colors disabled:opacity-50"
                >
                  <Calendar className="h-4 w-4" />
                  Absagen (Zugesagte informiert)
                </button>
              ) : null}
              {isScheduled && onArchiveQuiet ? (
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    setOpen(false);
                    onArchiveQuiet();
                  }}
                  disabled={isStarting}
                  className="flex w-full items-center gap-2 px-3 py-2 text-left font-barlow text-sm uppercase text-gray-300 hover:bg-hero-dark hover:text-white transition-colors disabled:opacity-50"
                >
                  <Archive className="h-4 w-4" />
                  Archivieren (ohne Nachricht)
                </button>
              ) : null}
              {allowDelete && (!hasAcceptedRsvps || !isScheduled) ? (
                <button
                  type="button"
                  onClick={(e) => {
                    e.stopPropagation();
                    setOpen(false);
                    onDelete();
                  }}
                  disabled={isStarting}
                  className="flex w-full items-center gap-2 px-3 py-2 text-left font-barlow text-sm uppercase text-red-400 hover:bg-red-900/30 transition-colors disabled:opacity-50"
                >
                  <Trash2 className="h-4 w-4" />
                  Löschen
                </button>
              ) : null}
            </>
          )}
        </div>
      )}
    </div>
  );
}

type Props = {
  campaignId: string;
  worldId?: string | null;
  isGM: boolean;
  characterStatus?: string;
  focusSession: SessionItem | null;
  otherUpcomingSessions: SessionItem[];
  pastSessionRows: SessionItem[];
  /** Vollständige aktive Liste (Fokus zuerst) */
  upcomingSessions: SessionItem[];
  archives?: SessionArchiveItem[];
  latestPublishedPlayerRecap?: LatestPublishedPlayerRecap | null;
  locations: Array<{ id: string; name: string; type: string }>;
  npcs: Array<{ id: string; name: string; title: string | null }>;
};

export function SessionsTab({
  campaignId,
  worldId = null,
  isGM,
  characterStatus,
  focusSession,
  otherUpcomingSessions,
  pastSessionRows,
  upcomingSessions: _upcomingSessions,
  archives = [],
  latestPublishedPlayerRecap = null,
  locations,
  npcs,
}: Props) {
  const canJoinSession = isGM || characterStatus === "Active";
  const [isWizardOpen, setIsWizardOpen] = useState(false);
  const [wizardEditSession, setWizardEditSession] = useState<SessionItem | null>(null);
  const [isEventModalOpen, setIsEventModalOpen] = useState(false);
  const [editingSession, setEditingSession] = useState<SessionItem | null>(null);
  const [startBgSessionId, setStartBgSessionId] = useState<string | null>(null);
  const [isStarting, startTransition] = useTransition();
  const [wrapUpSessionId, setWrapUpSessionId] = useState<string | null>(null);
  const [pane, setPane] = useState<"next" | "running" | "archive">("next");
  const router = useRouter();

  const handleSuccess = (sessionId?: string) => {
    setWizardEditSession(null);
    router.refresh();
    if (sessionId) {
      toast.success("Session gespeichert", {
        action: {
          label: "Bühnenvorbereitung",
          onClick: () =>
            router.push(
              `/dashboard/campaigns/${campaignId}/sessions/${sessionId}/stage-prep`,
            ),
        },
      });
    }
  };

  const openKiWizard = (session: SessionItem | null) => {
    setWizardEditSession(session);
    setIsWizardOpen(true);
  };

  function renderKiWizardButton(session: SessionItem, variant: "compact" | "panel" = "compact") {
    if (!isGM || !isSessionStatusScheduled(session.status)) return null;
    if (!sessionSupportsLiveBoard(session.type)) return null;
    const needsPlanning =
      session.gm_prep_complete === false || isAutoGeneratedSessionTitle(session.title);
    if (!needsPlanning) return null;
    if (variant === "panel") {
      return (
        <button type="button" onClick={() => openKiWizard(session)} className={panelActionClass}>
          <Wand2 className="h-4 w-4 text-fuchsia-300" />
          Mit KI planen
        </button>
      );
    }
    return (
      <button
        type="button"
        onClick={() => openKiWizard(session)}
        className="inline-flex items-center gap-1 rounded border border-hero-vibrant/50 bg-hero-vibrant/10 px-3 py-1.5 font-barlow font-bold uppercase text-[10px] text-hero-vibrant hover:bg-hero-vibrant/20 transition-colors"
      >
        <Wand2 className="h-3.5 w-3.5" />
        Mit KI planen
      </button>
    );
  }

  const handleDelete = (sessionId: string) => {
    if (!confirm("Termin wirklich löschen? Dies kann nicht rückgängig gemacht werden.")) return;
    startTransition(async () => {
      try {
        await deleteSession(sessionId);
        router.refresh();
      } catch (err: unknown) {
        alert((err as Error).message || "Fehler beim Löschen.");
      }
    });
  };

  const handleStartSession = (sessionId: string) => {
    if (isStarting) return;
    setStartBgSessionId(sessionId);
  };

  const handleMarkPrepComplete = (sessionId: string) => {
    if (isStarting) return;
    startTransition(async () => {
      try {
        await markSessionPlanningComplete(sessionId);
        router.refresh();
      } catch (err: unknown) {
        alert((err as Error).message || "Planung konnte nicht gespeichert werden.");
      }
    });
  };

  const handleJoinLive = (sessionId: string) => {
    router.push(`/session/${sessionId}`);
  };

  const handleCancel = (sessionId: string) => {
    if (
      !confirm(
        "Termin absagen? Nur Spieler mit Zusage oder „Via Online“ erhalten eine Nachricht in ihrer Nachrichten-Karte.",
      )
    )
      return;
    startTransition(async () => {
      try {
        await cancelSession(sessionId);
        router.refresh();
      } catch (err: unknown) {
        alert((err as Error).message || "Fehler beim Absagen.");
      }
    });
  };

  const handleEndSession = (sessionId: string) => {
    setWrapUpSessionId(sessionId);
  };

  const handleArchiveQuiet = (sessionId: string) => {
    if (
      !confirm(
        "Diesen geplanten Termin ohne Benachrichtigung an Spieler archivieren? Er verschwindet aus der Übersicht (Status: abgeschlossen).",
      )
    )
      return;
    startTransition(async () => {
      try {
        await archiveScheduledSessionQuietly(sessionId);
        router.refresh();
      } catch (err: unknown) {
        alert((err as Error).message || "Archivieren fehlgeschlagen.");
      }
    });
  };

  const handlePlanningDummy = (sessionId: string, next: number) => {
    if (isStarting) return;
    startTransition(async () => {
      try {
        await setPlanningDummyPlayerCount(sessionId, next);
        router.refresh();
      } catch (err: unknown) {
        alert((err as Error).message || "Platzhalter konnten nicht gespeichert werden.");
      }
    });
  };

  async function copySessionLink(sessionId: string) {
    const origin = typeof window !== "undefined" ? window.location.origin : "";
    const url = `${origin}/session/${sessionId}`;
    try {
      await navigator.clipboard.writeText(url);
      toast.success("Session-Link kopiert.");
    } catch {
      toast.error("Link konnte nicht kopiert werden.");
    }
  }

  function renderScheduleEditButton(session: SessionItem, variant: "compact" | "panel" = "compact") {
    if (!isGM || !canEditSessionSchedule(session.status)) return null;
    if (variant === "panel") {
      return (
        <button type="button" onClick={() => setEditingSession(session)} className={panelActionClass}>
          <CalendarClock className="h-4 w-4 text-emerald-300" />
          Termin ändern
        </button>
      );
    }
    return (
      <button
        type="button"
        onClick={() => setEditingSession(session)}
        className="inline-flex items-center gap-1.5 rounded border border-hero-border/50 bg-hero-dark/50 px-3 py-1.5 font-barlow text-[10px] font-bold uppercase text-gray-300 hover:border-hero-vibrant hover:text-hero-vibrant transition-colors"
      >
        <Pencil className="h-3.5 w-3.5" />
        Termin ändern
      </button>
    );
  }

  function renderSessionActions(session: SessionItem, allowDelete = false) {
    const live = isSessionStatusLive(session.status);
    const scheduled = isSessionStatusScheduled(session.status);
    const canSchedule = canEditSessionSchedule(session.status);
    const terminal = isSessionStatusTerminal(session.status);
    if (!isGM || (!scheduled && !live && !terminal)) return null;
    return (
      <SessionActionsDropdown
        isStarting={isStarting}
        onEditSchedule={canSchedule ? () => setEditingSession(session) : undefined}
        canEditSchedule={canSchedule}
        onDelete={() => handleDelete(session.id)}
        onCancel={scheduled ? () => handleCancel(session.id) : undefined}
        onArchiveQuiet={
          scheduled ? () => handleArchiveQuiet(session.id) : undefined
        }
        onEnd={live ? () => handleEndSession(session.id) : undefined}
        hasAcceptedRsvps={session.hasAcceptedRsvps}
        isLive={live}
        isScheduled={scheduled}
        allowDelete={allowDelete}
      />
    );
  }

  function renderScheduledGmControls(session: SessionItem) {
    if (!isGM || !isSessionStatusScheduled(session.status)) return null;
    if (!sessionSupportsLiveBoard(session.type)) {
      return (
        <p className="font-libre text-xs text-gray-500 italic">
          Termin ohne Live-Bühne — Spieler melden sich per RSVP an.
        </p>
      );
    }
    return (
      <div className="flex flex-col gap-2">
        {(session.pendingCount ?? 0) > 0 ? (
          <p className="font-libre text-[11px] text-amber-300">
            {session.pendingCount} ohne Rückmeldung (−2 Punkte beim Start)
          </p>
        ) : null}
        {session.canStart ? (
          <button
            type="button"
            onClick={() => handleStartSession(session.id)}
            disabled={isStarting}
            className={panelActionClass}
          >
            <Play className="h-4 w-4 text-hero-vibrant" />
            Session starten
          </button>
        ) : session.gm_prep_complete === false ? (
          <button
            type="button"
            onClick={() => handleMarkPrepComplete(session.id)}
            disabled={isStarting}
            className={panelActionClass}
          >
            <ClipboardCheck className="h-4 w-4 text-amber-300" />
            Planung abschließen
          </button>
        ) : null}
        {renderKiWizardButton(session, "panel")}
        <Link href={`/session/${session.id}`} className={panelActionClass}>
          <Sparkles className="h-4 w-4 text-accent-gold" />
          Tisch vorbereiten
        </Link>
        <Link
          href={`/dashboard/campaigns/${campaignId}/sessions/${session.id}/stage-prep#szenen-mediathek`}
          className={panelActionClass}
          title="Szenen-Bilder hochladen und ins Bühnendeck legen"
        >
          <Images className="h-4 w-4 text-cyan-300" />
          Szenen-Mediathek
        </Link>
        {renderScheduleEditButton(session, "panel")}
      </div>
    );
  }

  const nextSession =
    focusSession &&
    !isSessionStatusTerminal(focusSession.status) &&
    !isMissedScheduledSession(focusSession) &&
    !(isSessionStatusLive(focusSession.status) && isStaleLiveSession(focusSession))
      ? focusSession
      : null;

  const seenIds = new Set<string>();
  const allSessions = [focusSession, ...otherUpcomingSessions, ...pastSessionRows].filter(
    (session): session is SessionItem => {
      if (!session || seenIds.has(session.id)) return false;
      seenIds.add(session.id);
      return true;
    },
  );

  const upcomingCards = allSessions
    .filter(
      (session) =>
        session.id !== nextSession?.id &&
        isSessionStatusScheduled(session.status) &&
        !isMissedScheduledSession(session),
    )
    .sort((a, b) => new Date(a.start_time).getTime() - new Date(b.start_time).getTime());

  const runningSessions = allSessions
    .filter((session) => {
      if (nextSession && session.id === nextSession.id) return false;
      if (isSessionStatusTerminal(session.status)) return false;
      return isSessionStatusLive(session.status);
    })
    .sort((a, b) => new Date(b.start_time).getTime() - new Date(a.start_time).getTime());

  const archivedSessions = allSessions
    .filter(
      (session) =>
        isSessionStatusTerminal(session.status) || isMissedScheduledSession(session),
    )
    .sort((a, b) => new Date(b.start_time).getTime() - new Date(a.start_time).getTime());

  return (
    <>
      <StartSessionBackgroundModal
        open={startBgSessionId != null}
        sessionId={startBgSessionId}
        onOpenChange={(open) => !open && setStartBgSessionId(null)}
        onStarted={(sid) => router.push(`/session/${sid}`)}
      />
      <div className="rounded-lg border border-hero-dark bg-background-card p-6">
        <div className="flex items-center justify-between mb-4 pb-2 border-b border-hero-dark">
          <h2 className="font-barlow font-bold text-xl text-white uppercase flex items-center gap-2">
            <Calendar className="h-5 w-5 text-accent-gold" />
            Termine
          </h2>
          {isGM && (
            <div className="flex flex-wrap items-center gap-2">
              <button
                type="button"
                onClick={() => setIsEventModalOpen(true)}
                className="flex items-center gap-1 rounded border border-hero-border bg-background-dark px-3 py-1.5 font-barlow font-bold uppercase text-xs text-hero-vibrant hover:border-hero-vibrant transition-colors"
              >
                <Plus className="h-4 w-4" />
                Spielplanung
              </button>
              <button
                type="button"
                onClick={() => openKiWizard(null)}
                className="flex items-center gap-1 rounded bg-hero-dark px-3 py-1.5 font-barlow font-bold uppercase text-xs text-white hover:bg-hero-vibrant transition-colors"
                title="Neuen Spielabend mit KI-Wizard anlegen"
              >
                <Wand2 className="h-4 w-4" />
                Neuer Spielabend (KI)
              </button>
            </div>
          )}
        </div>

        <div className="mb-6 flex flex-wrap gap-2" role="tablist" aria-label="Session-Bereiche">
          {(
            [
              ["next", "Nächste Session", nextSession ? 1 : 0],
              ["running", "Laufende Sessions", runningSessions.length],
              ["archive", "Archiviert", archivedSessions.length],
            ] as const
          ).map(([id, label, count]) => {
            const active = pane === id;
            const alert = id === "running" && count > 0;
            return (
              <button
                key={id}
                type="button"
                role="tab"
                aria-selected={active}
                onClick={() => setPane(id)}
                className={`inline-flex items-center gap-2 rounded-md border px-3 py-2 font-barlow text-xs font-bold uppercase tracking-wide transition-colors ${
                  active
                    ? alert
                      ? "border-amber-500 bg-amber-950/50 text-amber-100"
                      : "border-hero-vibrant bg-hero-vibrant/15 text-hero-vibrant"
                    : alert
                      ? "border-amber-700/70 bg-amber-950/20 text-amber-200 hover:border-amber-500"
                      : "border-hero-border/40 bg-background-dark text-gray-400 hover:border-hero-vibrant hover:text-white"
                }`}
              >
                {label}
                <span
                  className={`rounded px-1.5 py-0.5 text-[10px] ${
                    alert ? "bg-amber-500 text-black" : "bg-black/30 text-gray-300"
                  }`}
                >
                  {count}
                </span>
              </button>
            );
          })}
        </div>

        {pane === "next" ? (
          <div className="space-y-8">
            {!isGM && latestPublishedPlayerRecap ? (
              <LastSessionRecapCard
                campaignId={campaignId}
                worldId={worldId}
                recap={latestPublishedPlayerRecap}
              />
            ) : null}
            {!nextSession ? (
              <p className="font-libre text-gray-400 text-center py-8">
                Kein anstehender Termin. Lege eine neue Session an.
              </p>
            ) : (
              (() => {
                const session = nextSession;
                const { formattedDate, formattedTime } = formatSessionDateTime(session.start_time);
                const live = isSessionStatusLive(session.status);
                const scheduled = isSessionStatusScheduled(session.status);
                const graceOverdue = isScheduledInGraceOverdue(session);
                const CardInner = (
                  <div className={`relative overflow-hidden rounded-xl border-2 bg-background-dark p-6 ${sessionCardBorderClass(session)}`}>
                    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                      <div>
                        {live ? (
                          <span className="mb-2 inline-flex items-center gap-2 rounded-full border border-red-500/70 bg-red-950/50 px-3 py-1 font-barlow text-[10px] font-extrabold uppercase tracking-widest text-red-200">
                            <Radio className="h-3.5 w-3.5 animate-pulse text-red-400" />
                            Jetzt live
                          </span>
                        ) : null}
                        {scheduled && graceOverdue ? (
                          <span className="mb-2 inline-flex items-center gap-2 rounded-full border border-amber-600/70 bg-amber-950/40 px-3 py-1 font-barlow text-[10px] font-extrabold uppercase tracking-widest text-amber-100">
                            Noch nicht gestartet ({SCHEDULED_NOT_STARTED_GRACE_HOURS}h Toleranz)
                          </span>
                        ) : null}
                        <h3 className="font-cinzel text-2xl font-bold text-white">
                          {session.title || "Session"}
                        </h3>
                        <p className="mt-2 font-barlow text-sm uppercase text-accent-gold">
                          {formattedDate} · {formattedTime} Uhr
                        </p>
                        <p className="mt-1 font-libre text-xs text-gray-500">
                          {getSessionTypeLabel(session.type)}
                        </p>
                      </div>
                      {renderSessionActions(session)}
                    </div>

                    <div className="mt-5 grid gap-3 border-t border-hero-border/30 pt-4 sm:grid-cols-2">
                      <div className="flex flex-col gap-2">
                        <p className="font-barlow text-[10px] font-bold uppercase text-gray-500">Sitzung</p>
                        {live && canJoinSession && sessionSupportsLiveBoard(session.type) ? (
                          <button
                            type="button"
                            onClick={() => handleJoinLive(session.id)}
                            className={panelActionClass}
                          >
                            <LogIn className="h-4 w-4 text-red-400" />
                            Sitzung beitreten
                          </button>
                        ) : null}
                        {live && isGM ? (
                          <button
                            type="button"
                            onClick={() => handleEndSession(session.id)}
                            disabled={isStarting}
                            className={panelActionClass}
                          >
                            <Square className="h-4 w-4 text-amber-300" />
                            Session abschließen
                          </button>
                        ) : null}
                        {isGM && live && sessionSupportsLiveBoard(session.type) ? (
                          <button
                            type="button"
                            onClick={() => void copySessionLink(session.id)}
                            className={panelActionClass}
                          >
                            <Copy className="h-4 w-4 text-sky-300" />
                            Session-Link kopieren
                          </button>
                        ) : null}
                        {scheduled && isGM && session.canStart && sessionSupportsLiveBoard(session.type) ? (
                          <button
                            type="button"
                            onClick={() => handleStartSession(session.id)}
                            disabled={isStarting}
                            className={panelActionClass}
                          >
                            <Play className="h-4 w-4 text-hero-vibrant" />
                            Session starten
                          </button>
                        ) : null}
                        {scheduled && isGM && !session.canStart && session.gm_prep_complete === false ? (
                          <button
                            type="button"
                            onClick={() => handleMarkPrepComplete(session.id)}
                            disabled={isStarting}
                            className={panelActionClass}
                          >
                            <ClipboardCheck className="h-4 w-4 text-amber-300" />
                            Planung abschließen
                          </button>
                        ) : null}
                      </div>
                      <div className="flex flex-col gap-2">
                        <p className="font-barlow text-[10px] font-bold uppercase text-gray-500">Vorbereitung</p>
                        {renderKiWizardButton(session, "panel")}
                        {isGM && (scheduled || live) && sessionSupportsLiveBoard(session.type) ? (
                          <>
                            <Link
                              href={`/session/${session.id}`}
                              className={panelActionClass}
                            >
                              <Sparkles className="h-4 w-4 text-accent-gold" />
                              Tisch vorbereiten
                            </Link>
                            <Link
                              href={`/dashboard/campaigns/${campaignId}/sessions/${session.id}/stage-prep#szenen-mediathek`}
                              className={panelActionClass}
                            >
                              <Images className="h-4 w-4 text-cyan-300" />
                              Szenen-Mediathek
                            </Link>
                          </>
                        ) : null}
                        {renderScheduleEditButton(session, "panel")}
                      </div>
                    </div>

                    {scheduled && isGM && (session.pendingCount ?? 0) > 0 ? (
                      <p className="mt-3 font-libre text-xs text-amber-300">
                        Noch {session.pendingCount} Spieler ohne Rückmeldung (−2 Punkte beim Start).
                      </p>
                    ) : null}

                    {isGM && (scheduled || live) && sessionSupportsLiveBoard(session.type) ? (
                      <div className="mt-4 border-t border-hero-border/30 pt-4">
                        <p className="font-barlow text-[10px] font-bold uppercase text-gray-500">Platzhalter am Tisch</p>
                        <div className="mt-3 flex items-center gap-1 rounded border border-hero-border/50 bg-hero-dark/40 p-1 w-fit">
                          <button
                            type="button"
                            disabled={isStarting || (session.planning_dummy_player_count ?? 0) <= 0}
                            onClick={() =>
                              handlePlanningDummy(
                                session.id,
                                Math.max(0, (Math.round(Number(session.planning_dummy_player_count ?? 0)) || 0) - 1),
                              )
                            }
                            className="grid h-8 w-8 place-items-center rounded font-barlow text-lg font-bold text-white hover:bg-hero-dark disabled:opacity-40"
                            aria-label="Platzhalter entfernen"
                          >
                            −
                          </button>
                          <span className="min-w-[3.5rem] text-center font-barlow text-sm font-bold text-accent-gold">
                            {Math.min(3, Math.max(0, Math.round(Number(session.planning_dummy_player_count ?? 0)) || 0))} / 3
                          </span>
                          <button
                            type="button"
                            disabled={isStarting || (session.planning_dummy_player_count ?? 0) >= 3}
                            onClick={() =>
                              handlePlanningDummy(
                                session.id,
                                Math.min(3, (Math.round(Number(session.planning_dummy_player_count ?? 0)) || 0) + 1),
                              )
                            }
                            className="grid h-8 w-8 place-items-center rounded font-barlow text-lg font-bold text-white hover:bg-hero-dark disabled:opacity-40"
                            aria-label="Platzhalter hinzufügen"
                          >
                            +
                          </button>
                        </div>
                      </div>
                    ) : null}
                    {isGM && scheduled && sessionSupportsLiveBoard(session.type) ? (
                      <div className="mt-4 border-t border-hero-border/30 pt-4">
                        <SessionChronistModeControl
                          sessionId={session.id}
                          initialMode={parseTranscriptionMode(session.transcription_mode)}
                          variant="compact"
                          onModeChange={() => router.refresh()}
                        />
                      </div>
                    ) : null}
                  </div>
                );
                return live ? (
                  <motion.div
                    initial={{ opacity: 0, y: 12 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.35 }}
                    className="rounded-xl shadow-[0_0_28px_rgba(220,38,38,0.25)]"
                  >
                    {CardInner}
                  </motion.div>
                ) : (
                  <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35 }}>
                    {CardInner}
                  </motion.div>
                );
              })()
            )}

            {upcomingCards.length > 0 ? (
              <div>
                <h3 className="mb-3 font-barlow text-xs font-bold uppercase text-gray-500">
                  Weitere geplante Termine
                </h3>
                <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                  {upcomingCards.map((session) => {
                    const { formattedDate, formattedTime } = formatSessionDateTime(session.start_time);
                    return (
                      <article
                        key={session.id}
                        className={`flex aspect-[5/7] max-h-[28rem] flex-col justify-between rounded-xl border-2 bg-background-dark p-4 ${sessionCardBorderClass(session)}`}
                      >
                        <div>
                          <p className="font-barlow text-[10px] font-bold uppercase tracking-wide text-accent-gold">
                            {formattedDate}
                          </p>
                          <h4 className="mt-2 font-cinzel text-lg font-bold leading-snug text-white">
                            {session.title || "Session"}
                          </h4>
                          <p className="mt-1 font-libre text-xs text-gray-400">{formattedTime} Uhr</p>
                          <p className="mt-2 font-libre text-[11px] text-gray-500">
                            {getSessionTypeLabel(session.type)}
                          </p>
                        </div>
                        <div className="mt-4 flex min-h-0 flex-col gap-2 overflow-y-auto">
                          <div className="flex justify-end">{renderSessionActions(session)}</div>
                          {renderScheduledGmControls(session)}
                        </div>
                      </article>
                    );
                  })}
                </div>
              </div>
            ) : null}
          </div>
        ) : null}

        {pane === "running" ? (
          <div>
            {runningSessions.length === 0 ? (
              <p className="font-libre text-gray-400 text-center py-8">
                Keine offene Sitzung. Alles abgeschlossen.
              </p>
            ) : (
              <>
                <p className="mb-4 font-libre text-sm text-amber-100/90">
                  Diese Sitzungen laufen noch. Spieler können Notizen machen, bis du sie abschließt.
                  Danach wandern sie ins Archiv.
                </p>
                <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                  {runningSessions.map((session) => {
                    const { formattedDate, formattedTime } = formatSessionDateTime(session.start_time);
                    const stale = isStaleLiveSession(session);
                    const href = `/session/${session.id}`;
                    return (
                      <article
                        key={session.id}
                        className={`flex aspect-[5/7] max-h-[28rem] flex-col justify-between rounded-xl border-2 p-4 ${
                          stale
                            ? "border-amber-500 bg-amber-950/25 shadow-[0_0_18px_rgba(202,138,4,0.18)]"
                            : "border-red-700/70 bg-red-950/20"
                        }`}
                      >
                        <div>
                          <span className="inline-flex items-center gap-1.5 rounded-full border border-amber-500/70 bg-amber-500/15 px-2.5 py-1 font-barlow text-[10px] font-extrabold uppercase tracking-wide text-amber-100">
                            <Radio className="h-3 w-3" />
                            {stale ? "Offen lassen — noch nicht abgeschlossen" : "Läuft noch"}
                          </span>
                          <h4 className="mt-3 font-cinzel text-lg font-bold leading-snug text-white">
                            {session.title || "Session"}
                          </h4>
                          <p className="mt-2 font-barlow text-xs uppercase text-accent-gold">
                            {formattedDate} · {formattedTime} Uhr
                          </p>
                        </div>
                        <div className="mt-4 flex flex-col gap-2">
                          <Link
                            href={href}
                            className="inline-flex items-center justify-center gap-2 rounded-lg bg-amber-600 px-3 py-2 font-barlow text-[11px] font-extrabold uppercase text-black hover:bg-amber-500"
                          >
                            Live-Session öffnen
                          </Link>
                          <button
                            type="button"
                            onClick={() => void copySessionLink(session.id)}
                            className="inline-flex items-center justify-center gap-2 rounded-lg border border-accent-gold/50 px-3 py-2 font-barlow text-[11px] font-bold uppercase text-accent-gold hover:bg-accent-gold/10"
                          >
                            <Copy className="h-3.5 w-3.5" />
                            Link kopieren
                          </button>
                          {isGM ? (
                            <button
                              type="button"
                              onClick={() => handleEndSession(session.id)}
                              disabled={isStarting}
                              className="inline-flex items-center justify-center gap-2 rounded-lg border border-hero-border px-3 py-2 font-barlow text-[11px] font-bold uppercase text-white hover:border-hero-vibrant disabled:opacity-50"
                            >
                              <Square className="h-3.5 w-3.5" />
                              Abschließen
                            </button>
                          ) : null}
                        </div>
                      </article>
                    );
                  })}
                </div>
              </>
            )}
          </div>
        ) : null}

        {pane === "archive" ? (
          <div className="space-y-6">
            {archivedSessions.length === 0 && archives.length === 0 ? (
              <p className="font-libre text-gray-400 text-center py-8">Noch nichts archiviert.</p>
            ) : null}
            {archivedSessions.length > 0 ? (
              <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                {archivedSessions.map((session) => {
                  const { formattedDate, formattedTime } = formatSessionDateTime(session.start_time);
                  const missed = isMissedScheduledSession(session);
                  return (
                    <article
                      key={session.id}
                      className="flex aspect-[5/7] max-h-[28rem] flex-col justify-between rounded-xl border border-hero-border/30 bg-black/25 p-4"
                    >
                      <div>
                        <p className="font-barlow text-[10px] font-bold uppercase text-gray-500">
                          {pastSessionStatusLabel(session)}
                        </p>
                        <h4 className="mt-2 font-cinzel text-lg font-bold text-gray-200">
                          {session.title || "Session"}
                        </h4>
                        <p className="mt-2 font-libre text-xs text-gray-500">
                          {formattedDate} · {formattedTime} Uhr
                        </p>
                      </div>
                      {isGM ? (
                        <div className="mt-4 flex items-center justify-between gap-2">
                          {missed && sessionSupportsLiveBoard(session.type) ? (
                            <button
                              type="button"
                              disabled={isStarting}
                              onClick={() => handleStartSession(session.id)}
                              className="rounded border border-hero-vibrant/50 bg-hero-vibrant/10 px-2 py-1 font-barlow text-[10px] font-bold uppercase text-hero-vibrant disabled:opacity-50"
                            >
                              Starten
                            </button>
                          ) : (
                            <span />
                          )}
                          <SessionActionsDropdown
                            isStarting={isStarting}
                            onEditSchedule={
                              canEditSessionSchedule(session.status)
                                ? () => setEditingSession(session)
                                : undefined
                            }
                            canEditSchedule={canEditSessionSchedule(session.status)}
                            onDelete={() => handleDelete(session.id)}
                            onArchiveQuiet={
                              isSessionStatusScheduled(session.status)
                                ? () => handleArchiveQuiet(session.id)
                                : undefined
                            }
                            hasAcceptedRsvps={session.hasAcceptedRsvps}
                            isScheduled={isSessionStatusScheduled(session.status)}
                            allowDelete
                          />
                        </div>
                      ) : null}
                    </article>
                  );
                })}
              </div>
            ) : null}
            {archives.length > 0 ? (
              <PastSessionsGallery
                campaignId={campaignId}
                worldId={worldId}
                isGM={isGM}
                archives={archives}
              />
            ) : null}
          </div>
        ) : null}

      </div>

      {isGM && (
        <>
          <SessionWizardModal
            campaignId={campaignId}
            isOpen={isWizardOpen}
            onClose={() => {
              setIsWizardOpen(false);
              setWizardEditSession(null);
            }}
            locations={locations}
            npcs={npcs}
            onSuccess={handleSuccess}
            editSession={wizardEditSession}
          />
          <CampaignEventModal
            campaignId={campaignId}
            isOpen={isEventModalOpen}
            onClose={() => setIsEventModalOpen(false)}
            onSuccess={handleSuccess}
          />
          {editingSession && (
            <SessionEditModal
              session={editingSession}
              campaignId={campaignId}
              isOpen={!!editingSession}
              onClose={() => setEditingSession(null)}
              onSuccess={handleSuccess}
            />
          )}
          <SessionEndWrapUpModal
            open={wrapUpSessionId != null}
            onClose={() => setWrapUpSessionId(null)}
            sessionId={wrapUpSessionId ?? ""}
            campaignId={campaignId}
            isRecordingActive={false}
            onComplete={(path) => {
              setWrapUpSessionId(null);
              router.push(path);
            }}
          />
        </>
      )}
    </>
  );
}
