import type { ShopCatalogItem } from "../types";

export const ALCHEMIST_CATALOG: ShopCatalogItem[] = [
  {
    id: "pot-healing",
    name: "Heiltrank",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Gewöhnlich",
    priceGp: 50,
    weightLb: 0.5,
    effect: "Heilt 2W4 + 2 TP",
    attunement: false,
  },
  {
    id: "pot-healing-greater",
    name: "Heiltrank (groß)",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Ungewöhnlich",
    priceGp: 150,
    weightLb: 0.5,
    effect: "Heilt 4W4 + 4 TP",
    attunement: false,
  },
  {
    id: "pot-healing-superior",
    name: "Heiltrank (überlegen)",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Selten",
    priceGp: 450,
    weightLb: 0.5,
    effect: "Heilt 8W4 + 8 TP",
    attunement: false,
  },
  {
    id: "pot-antitoxin",
    name: "Gegengift (Antitoxin)",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Gewöhnlich",
    priceGp: 50,
    weightLb: 0,
    effect:
      "Vorteil auf Rettungswürfe gegen Gift, 1 Stunde lang (nach Einnehmen)",
    attunement: false,
  },
  {
    id: "alc-fire",
    name: "Alchemistenfeuer",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Gewöhnlich",
    priceGp: 50,
    weightLb: 1,
    effect:
      "Ziel brennt (1W4 Feuerschaden pro Runde), bis es gelöscht wird",
    attunement: false,
  },
  {
    id: "alc-acid",
    name: "Säurefläschchen",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Gewöhnlich",
    priceGp: 25,
    weightLb: 1,
    effect: "2W6 Säureschaden beim Aufprall auf ein Ziel",
    attunement: false,
  },
  {
    id: "alc-oil",
    name: "Öl (Flasche)",
    kind: "consumable",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceSp: 1,
    weightLb: 1,
    effect: "Erhöht Feuerschaden am brennenden Ziel um +5 (wenn angewendet)",
    attunement: false,
  },
  {
    id: "alc-smoke",
    name: "Rauchbombe",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Gewöhnlich",
    priceGp: 35,
    weightLb: 1,
    effect: "Erzeugt eine Rauchwolke (ca. 6 m Radius), die Sicht blockiert",
    attunement: false,
  },
  {
    id: "pot-climbing",
    name: "Trank des Kletterns",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Gewöhnlich",
    priceGp: 75,
    weightLb: 0.5,
    effect: "Klettertempo wie Gehtempo, Vorteil auf Athletik-Würfe beim Klettern",
    duration: "1 Stunde",
    attunement: false,
  },
  {
    id: "pot-water-breathing",
    name: "Trank des Wasseratmens",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Gewöhnlich",
    priceGp: 100,
    weightLb: 0.5,
    effect: "Atmen unter Wasser",
    duration: "1 Stunde",
    attunement: false,
  },
  {
    id: "pot-animal-friendship",
    name: "Trank der Tierfreundschaft",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Gewöhnlich",
    priceGp: 100,
    weightLb: 0.5,
    effect: "Wirkung wie Zauber Tierfreundschaft (SG 13)",
    duration: "1 Stunde",
    attunement: false,
  },
  {
    id: "pot-invisibility",
    name: "Trank der Unsichtbarkeit",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Selten",
    priceGp: 250,
    weightLb: 0.5,
    effect:
      "Vollständige Unsichtbarkeit; endet bei Angriff oder Zauberwirken",
    duration: "1 Stunde",
    attunement: false,
  },
  {
    id: "pot-giant-strength",
    name: "Trank der Riesenstärke (Hügelriese)",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Selten",
    weightLb: 0.5,
    priceLabel: "PHB / SL (seltener Trank)",
    effect:
      "Stärkewert 21, Angriffs- und Schadenswürfe mit Stärke haben Vorteil; Dauer und exakte Regeln PHB",
    duration: "1 Stunde",
    attunement: false,
  },
  {
    id: "tool-alchemist",
    name: "Alchemistenwerkzeuge",
    kind: "tool",
    categoryLabel: "Werkzeug",
    rarity: "Gewöhnlich",
    priceGp: 50,
    weightLb: 8,
    effect: "Herstellung und Identifikation alchemistischer Gegenstände",
    attunement: false,
  },
  {
    id: "supply-vial-empty",
    name: "Leere Glasfläschchen",
    kind: "supply",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 2,
    weightLb: 0,
    effect: "Behälter für Tränke und Flüssigkeiten",
    attunement: false,
  },
  {
    id: "supply-herbs",
    name: "Kräuter-Zusammenstellung",
    kind: "supply",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    weightLb: 1,
    priceLabel: "5–10 GP (variabel)",
    effect: "Zutaten für einfache alchemistische Experimente",
    notes: "Preis vom SL festlegen",
    attunement: false,
  },
];
