import type { ShopCatalogItem } from "../types";

/** Haus der Sehne & Esche — Bögen, Armbrüste, Munition, Zubehör (D&D 5e / deutsch) */
export const BOGENMACHER_CATALOG: ShopCatalogItem[] = [
  {
    id: "bow-short",
    name: "Kurzbogen",
    kind: "weapon",
    categoryLabel: "Fernkampfwaffe",
    rarity: "Gewöhnlich",
    priceGp: 25,
    weightLb: 2,
    damage: "1W6",
    damageType: "Stich",
    properties: ["Zweihändig", "Munition"],
    rangeMeters: "24/96",
    catalogGroup: "Bögen & Armbrüste (Grundausstattung)",
  },
  {
    id: "bow-long",
    name: "Langbogen",
    kind: "weapon",
    categoryLabel: "Fernkampfwaffe",
    rarity: "Gewöhnlich",
    priceGp: 50,
    weightLb: 2,
    damage: "1W8",
    damageType: "Stich",
    properties: ["Schwer", "Zweihändig", "Munition"],
    rangeMeters: "45/180",
    catalogGroup: "Bögen & Armbrüste (Grundausstattung)",
  },
  {
    id: "xbow-light",
    name: "Leichte Armbrust",
    kind: "weapon",
    categoryLabel: "Fernkampfwaffe",
    rarity: "Gewöhnlich",
    priceGp: 25,
    weightLb: 5,
    damage: "1W8",
    damageType: "Stich",
    properties: ["Zweihändig", "Laden", "Munition"],
    rangeMeters: "24/96",
    catalogGroup: "Bögen & Armbrüste (Grundausstattung)",
  },
  {
    id: "xbow-heavy",
    name: "Schwere Armbrust",
    kind: "weapon",
    categoryLabel: "Fernkampfwaffe",
    rarity: "Gewöhnlich",
    priceGp: 50,
    weightLb: 7,
    damage: "1W10",
    damageType: "Stich",
    properties: ["Schwer", "Zweihändig", "Laden", "Munition"],
    rangeMeters: "30/120",
    catalogGroup: "Bögen & Armbrüste (Grundausstattung)",
  },
  {
    id: "xbow-hand",
    name: "Handarmbrust",
    kind: "weapon",
    categoryLabel: "Fernkampfwaffe",
    rarity: "Gewöhnlich",
    priceGp: 75,
    weightLb: 3,
    damage: "1W6",
    damageType: "Stich",
    properties: ["Leicht", "Laden", "Munition"],
    rangeMeters: "9/36",
    catalogGroup: "Bögen & Armbrüste (Grundausstattung)",
  },
  {
    id: "ammo-arrows-standard",
    name: "Pfeile / Bolzen (20 Stück)",
    kind: "equipment",
    categoryLabel: "Munition",
    rarity: "Gewöhnlich",
    priceGp: 1,
    weightLb: 1,
    effect: "Standardmunition für Bögen und Armbrüste",
    catalogGroup: "Munition & Zubehör",
  },
  {
    id: "ammo-fire-arrows",
    name: "Brandpfeile (5 Stück)",
    kind: "consumable",
    categoryLabel: "Munition",
    rarity: "Gewöhnlich",
    priceGp: 10,
    weightLb: 0.5,
    effect:
      "Kleine Teer-Depots an der Spitze: beim Treffer +1 Feuerschaden, kann Entzündbares entzünden",
    catalogGroup: "Munition & Zubehör",
  },
  {
    id: "ammo-blunt-training",
    name: "Stumpfe Übungspfeile (20 Stück)",
    kind: "equipment",
    categoryLabel: "Munition",
    rarity: "Gewöhnlich",
    priceGp: 1,
    weightLb: 1,
    effect:
      "Verursachen Wuchtschaden statt Stichschaden — gut für Skelette oder Zielübungen",
    catalogGroup: "Munition & Zubehör",
  },
  {
    id: "ammo-whistle",
    name: "Pfeile mit Signalpfeife (5 Stück)",
    kind: "equipment",
    categoryLabel: "Munition",
    rarity: "Gewöhnlich",
    priceGp: 5,
    weightLb: 0.5,
    effect: "Schriller Ton beim Flug, bis ca. 150 m hörbar",
    catalogGroup: "Munition & Zubehör",
  },
  {
    id: "gear-quiver",
    name: "Köcher",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 1,
    weightLb: 1,
    effect: "Fasst bis zu 20 Pfeile oder Bolzen",
    catalogGroup: "Munition & Zubehör",
  },
  {
    id: "gear-bolt-case",
    name: "Armbrustbolzen-Etui",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 1,
    weightLb: 1,
    effect: "Sichere Aufbewahrung für Bolzen",
    catalogGroup: "Munition & Zubehör",
  },
  {
    id: "gear-strings",
    name: "Ersatzsehnen (Set)",
    kind: "equipment",
    categoryLabel: "Zubehör",
    rarity: "Gewöhnlich",
    priceSp: 5,
    weightLb: 0,
    effect:
      "Für optionalen Hausregel: Sehne kann bei natürlicher 1 reißen — immer griffbereit",
    catalogGroup: "Munition & Zubehör",
  },
  {
    id: "gear-bow-wax",
    name: "Bogenwachs",
    kind: "equipment",
    categoryLabel: "Pflege",
    rarity: "Gewöhnlich",
    priceSp: 2,
    weightLb: 0,
    effect: "Hält das Holz geschmeidig — reiner Flavor-Gegenstand",
    catalogGroup: "Munition & Zubehör",
  },
  {
    id: "gear-arm-guard",
    name: "Armschutz aus Leder",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 1,
    weightLb: 0,
    effect: "Schützt den Unterarm vor der peitschenden Sehne",
    catalogGroup: "Munition & Zubehör",
  },
  {
    id: "gear-crossbow-sight",
    name: "Präzisionsvisier (für Armbrüste)",
    kind: "equipment",
    categoryLabel: "Zubehör",
    rarity: "Gewöhnlich",
    priceGp: 50,
    weightLb: 0,
    effect:
      "Feine mechanische Vorrichtung: effektive Reichweite ohne Nachteil um 3 m erhöht (SL bestätigen)",
    catalogGroup: "Munition & Zubehör",
  },
];
