import type { ShopCatalogItem } from "../types";

/**
 * Gemischtwarenhändler — Preise nach D&D 5e (PHB Abenteurerausrüstung).
 */
export const GEMISCHTWAREN_CATALOG: ShopCatalogItem[] = [
  {
    id: "misc-lockpicks",
    name: "Dietrich-Set",
    kind: "tool",
    categoryLabel: "Werkzeug",
    rarity: "Gewöhnlich",
    priceGp: 25,
    weightLb: 0,
    effect: "Für die geschickten Nachtklingen",
    catalogGroup: "Werkzeug & Vorräte",
  },
  {
    id: "misc-healer-kit",
    name: "Heilset (10 Anwendungen)",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 5,
    weightLb: 3,
    effect: "Von Friedenshütern gesegnet",
    catalogGroup: "Werkzeug & Vorräte",
  },
  {
    id: "misc-herbalism-kit",
    name: "Kräuterkunde-Set",
    kind: "tool",
    categoryLabel: "Werkzeug",
    rarity: "Gewöhnlich",
    priceGp: 5,
    weightLb: 3,
    effect: "Um Tränke selbst zu brauen",
    catalogGroup: "Werkzeug & Vorräte",
  },
  {
    id: "misc-vial-empty",
    name: "Leere Glasflasche",
    kind: "supply",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 1,
    weightLb: 0,
    effect: "Für Proben oder Tränke",
    catalogGroup: "Werkzeug & Vorräte",
  },
  {
    id: "misc-lantern",
    name: "Laterne (geschlossen)",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 5,
    weightLb: 1,
    effect: "Standard-Lichtquelle",
    catalogGroup: "Licht & Feuer",
  },
  {
    id: "misc-oil",
    name: "Öl (Fläschchen)",
    kind: "consumable",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceSp: 1,
    weightLb: 1,
    effect: "Für Laternen oder Brandstiftung",
    catalogGroup: "Licht & Feuer",
  },
  {
    id: "misc-chalk",
    name: "Kreide (1 Stück)",
    kind: "supply",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceCp: 1,
    weightLb: 0,
    effect: "Pfade in Dungeons markieren",
    catalogGroup: "Werkzeug & Vorräte",
  },
  {
    id: "misc-mirror",
    name: "Spiegel (Stahl)",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 5,
    weightLb: 0.5,
    effect: "Nützlich gegen Medusen und ähnliches",
    catalogGroup: "Werkzeug & Vorräte",
  },
  {
    id: "misc-backpack",
    name: "Rucksack (Leder)",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 2,
    weightLb: 5,
    effect: "Entspricht ca. 2 GP Standardausrüstung",
    catalogGroup: "Reise & Lager",
  },
  {
    id: "misc-bedroll",
    name: "Schlafsack (gefüttert)",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 1,
    weightLb: 3,
    effect: "Warm schlafen unter freiem Himmel",
    catalogGroup: "Reise & Lager",
  },
  {
    id: "misc-rations",
    name: "Abenteurer-Rationen (1 Tag)",
    kind: "consumable",
    categoryLabel: "Verbrauchsgut",
    rarity: "Gewöhnlich",
    priceSp: 2,
    weightLb: 2,
    effect: "1 Tag Proviant (PHB)",
    catalogGroup: "Reise & Lager",
  },
  {
    id: "misc-waterskin",
    name: "Wasserschlauch (gefüllt)",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceSp: 2,
    weightLb: 5,
    effect: "Entspricht ca. 2 SP",
    catalogGroup: "Reise & Lager",
  },
  {
    id: "misc-torch",
    name: "Fackel (brennt 1 Stunde)",
    kind: "consumable",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceCp: 1,
    weightLb: 1,
    effect: "Offenes Licht",
    catalogGroup: "Licht & Feuer",
  },
  {
    id: "misc-tinderbox",
    name: "Zunderkästchen",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceSp: 5,
    weightLb: 0,
    effect: "Feuer machen",
    catalogGroup: "Licht & Feuer",
  },
  {
    id: "misc-rope",
    name: "Hanfseil (15 Meter)",
    kind: "equipment",
    categoryLabel: "Abenteurerausrüstung",
    rarity: "Gewöhnlich",
    priceGp: 1,
    weightLb: 10,
    effect: "Entspricht ca. 1 GP",
    catalogGroup: "Werkzeug & Vorräte",
  },
  {
    id: "misc-rose-water",
    name: "Elysisches Rosenwasser",
    kind: "consumable",
    categoryLabel: "Luxus",
    rarity: "Gewöhnlich",
    priceGp: 2,
    weightLb: 0,
    effect: "Parfüm: +1 auf Überreden, 1 Stunde lang",
    duration: "1 Stunde",
    catalogGroup: "Kuriositäten & Luxus",
  },
  {
    id: "misc-whetstone",
    name: "Schleifstein",
    kind: "equipment",
    categoryLabel: "Werkzeug",
    rarity: "Gewöhnlich",
    priceCp: 1,
    weightLb: 1,
    effect: "Hält Klingen scharf",
    catalogGroup: "Kuriositäten & Luxus",
  },
  {
    id: "misc-tobacco",
    name: "Blauer Sternen-Tabak",
    kind: "consumable",
    categoryLabel: "Luxus",
    rarity: "Gewöhnlich",
    priceSp: 3,
    weightLb: 0,
    effect: "Sehr beliebt bei Anhängern des Fatum",
    catalogGroup: "Kuriositäten & Luxus",
  },
  {
    id: "misc-luck-charm",
    name: "Glücksbringer (Sperling)",
    kind: "equipment",
    categoryLabel: "Kuriosität",
    rarity: "Gewöhnlich",
    priceGp: 1,
    weightLb: 0,
    effect: "Kleiner geschnitzter Vogel von Fedrix — reiner Flavor, kein mechanischer Bonus",
    catalogGroup: "Kuriositäten & Luxus",
  },
];
