import type { ShopCatalogItem } from "../types";

/** PHB-typische Rüstungen und Schild (Preise in GP, Gewicht in lb.) */
export const RUSTUNGSSCHMIED_CATALOG: ShopCatalogItem[] = [
  {
    id: "armor-padded",
    name: "Polsterrüstung",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 5,
    weightLb: 8,
    acFormula: "11 + GE-Modifikator",
    stealthDisadvantage: true,
  },
  {
    id: "armor-leather",
    name: "Lederrüstung",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 10,
    weightLb: 10,
    acFormula: "11 + GE-Modifikator",
  },
  {
    id: "armor-studded",
    name: "Beschlagenes Leder",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 45,
    weightLb: 13,
    acFormula: "12 + GE-Modifikator",
  },
  {
    id: "armor-hide",
    name: "Fellrüstung",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 10,
    weightLb: 12,
    acFormula: "12 + GE (max. +2)",
  },
  {
    id: "armor-chain-shirt",
    name: "Kettenhemd",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 50,
    weightLb: 20,
    acFormula: "13 + GE (max. +2)",
  },
  {
    id: "armor-scale",
    name: "Schuppenpanzer",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 50,
    weightLb: 45,
    acFormula: "14 + GE (max. +2)",
    stealthDisadvantage: true,
  },
  {
    id: "armor-breastplate",
    name: "Brustpanzer",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 400,
    weightLb: 20,
    acFormula: "14 + GE (max. +2)",
  },
  {
    id: "armor-half-plate",
    name: "Halbharnisch",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 750,
    weightLb: 40,
    acFormula: "15 + GE (max. +2)",
    stealthDisadvantage: true,
  },
  {
    id: "armor-ring",
    name: "Ringpanzer",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 30,
    weightLb: 40,
    acFormula: "14",
    stealthDisadvantage: true,
  },
  {
    id: "armor-chain-mail",
    name: "Kettenpanzer",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 75,
    weightLb: 55,
    acFormula: "16",
    strRequirement: 13,
    stealthDisadvantage: true,
  },
  {
    id: "armor-splint",
    name: "Schienenpanzer",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 200,
    weightLb: 60,
    acFormula: "17",
    strRequirement: 15,
    stealthDisadvantage: true,
  },
  {
    id: "armor-plate",
    name: "Ritterrüstung",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 1500,
    weightLb: 65,
    acFormula: "18",
    strRequirement: 15,
    stealthDisadvantage: true,
  },
  {
    id: "armor-shield",
    name: "Schild",
    kind: "armor",
    categoryLabel: "Rüstung",
    rarity: "Gewöhnlich",
    priceGp: 10,
    weightLb: 6,
    isShield: true,
  },
];
