import type { ShopCatalogItem } from "../types";

/** Einfache und kriegerische Nahkampfwaffen (D&D 5e, deutsch) */
export const WAFFENMEISTER_CATALOG: ShopCatalogItem[] = [
  {
    id: "wpn-dagger",
    name: "Dolch",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 2,
    weightLb: 1,
    damage: "1W4",
    damageType: "Stich",
    properties: ["Finesse", "Leicht", "Wurfwaffe"],
    rangeMeters: "6/18",
    catalogGroup: "Einfache Nahkampfwaffen",
  },
  {
    id: "wpn-handaxe",
    name: "Handbeil",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 5,
    weightLb: 2,
    damage: "1W6",
    damageType: "Hieb",
    properties: ["Leicht", "Wurfwaffe"],
    rangeMeters: "6/18",
    catalogGroup: "Einfache Nahkampfwaffen",
  },
  {
    id: "wpn-spear",
    name: "Speer",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 1,
    weightLb: 3,
    damage: "1W6",
    damageType: "Stich",
    properties: ["Wurfwaffe", "Vielseitig (1W8)"],
    rangeMeters: "6/18",
    catalogGroup: "Einfache Nahkampfwaffen",
  },
  {
    id: "wpn-mace",
    name: "Streitkolben",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 5,
    weightLb: 4,
    damage: "1W6",
    damageType: "Wucht",
    catalogGroup: "Einfache Nahkampfwaffen",
  },
  {
    id: "wpn-quarterstaff",
    name: "Quartierstab",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceSp: 2,
    weightLb: 4,
    damage: "1W6",
    damageType: "Wucht",
    properties: ["Vielseitig (1W8)"],
    catalogGroup: "Einfache Nahkampfwaffen",
  },
  {
    id: "wpn-lance",
    name: "Lanze",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 2,
    weightLb: 6,
    damage: "1W8",
    damageType: "Stich",
    properties: ["Zweihändig"],
    notes: "Spezialregeln Lanze (PHB)",
    catalogGroup: "Einfache Nahkampfwaffen",
  },
  {
    id: "wpn-broadsword",
    name: "Breitschwert",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 15,
    weightLb: 3,
    damage: "1W8",
    damageType: "Hieb",
    catalogGroup: "Kriegerische Nahkampfwaffen",
  },
  {
    id: "wpn-longsword",
    name: "Langschwert",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 15,
    weightLb: 3,
    damage: "1W8",
    damageType: "Hieb",
    properties: ["Vielseitig (1W10)"],
    catalogGroup: "Kriegerische Nahkampfwaffen",
  },
  {
    id: "wpn-greatsword",
    name: "Zweihänder",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 50,
    weightLb: 6,
    damage: "2W6",
    damageType: "Hieb",
    properties: ["Schwer", "Zweihändig"],
    catalogGroup: "Kriegerische Nahkampfwaffen",
  },
  {
    id: "wpn-rapier",
    name: "Rapier",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 25,
    weightLb: 2,
    damage: "1W8",
    damageType: "Stich",
    properties: ["Finesse"],
    catalogGroup: "Kriegerische Nahkampfwaffen",
  },
  {
    id: "wpn-scimitar",
    name: "Krummsäbel",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 25,
    weightLb: 3,
    damage: "1W6",
    damageType: "Hieb",
    properties: ["Finesse", "Leicht"],
    catalogGroup: "Kriegerische Nahkampfwaffen",
  },
  {
    id: "wpn-battleaxe",
    name: "Streitaxt",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 10,
    weightLb: 4,
    damage: "1W8",
    damageType: "Hieb",
    properties: ["Vielseitig (1W10)"],
    catalogGroup: "Kriegerische Nahkampfwaffen",
  },
  {
    id: "wpn-halberd",
    name: "Hellebarde",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 20,
    weightLb: 6,
    damage: "1W10",
    damageType: "Hieb",
    properties: ["Schwer", "Reichweite", "Zweihändig"],
    catalogGroup: "Kriegerische Nahkampfwaffen",
  },
  {
    id: "wpn-maul",
    name: "Streitkolben (schwer)",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 10,
    weightLb: 2,
    damage: "1W8",
    damageType: "Wucht",
    catalogGroup: "Kriegerische Nahkampfwaffen",
  },
  {
    id: "wpn-warhammer",
    name: "Kriegshammer",
    kind: "weapon",
    categoryLabel: "Waffe",
    rarity: "Gewöhnlich",
    priceGp: 15,
    weightLb: 2,
    damage: "1W8",
    damageType: "Wucht",
    properties: ["Vielseitig (1W10)"],
    catalogGroup: "Kriegerische Nahkampfwaffen",
  },
];
