/**
 * LiveSessionBoardModalsLayer — Session modals, dice overlay, and token radial menu.
 */
"use client";

import { DiceRollOverlay } from "@/src/components/session/dice/DiceRollOverlay";
import { LiveSessionModals } from "./LiveSessionModals";
import { LiveSessionTokenRadialMenuHost } from "./LiveSessionTokenRadialMenuHost";
import { useLiveSessionBoardContext } from "./LiveSessionBoardContext";

export function LiveSessionBoardModalsLayer() {
  const {
    props: {
      sessionId,
      campaignId,
      worldId,
      sessionStatus,
      actualUserIsGM,
      isGuest,
      guestDisplayName,
      guestSlotIndex,
      forcePlayerView,
      userId,
      partyCharacters,
      allCampaignNpcs,
      allCampaignCreatures,
      stageDeckNpcIds,
      stageDeckCreatureIds,
      allSceneMedia,
      activeQuests,
      loreLocationOptions,
      sessionLocationLoreReadable,
      campaignShops,
      guestJoinUrl,
    },
    router,
    isGM,
    isUpdating,
    startTransition,
    bootstrap: {
      liveState,
      setLiveState,
      liveStateRef,
      isLiveStateInitializing,
      liveStateLoadError,
      backgroundUrl,
      resolveLiveStateBase,
      refreshLiveState,
    },
    chronicle: {
      activeTranscriptionMode,
      setActiveTranscriptionMode,
      chronistPanelOpen,
      setChronistPanelOpen,
      chronistStartFlowRef,
      chronistStopFlowRef,
      chronistSettingsFlowRef,
      recordingNoticeModalOpen,
      dismissChronistRecordingReminder,
      dismissJitsiChronistReminder,
      dismissRecordingNotice,
      isPrepMode,
      chronistTableMode,
      prepMicTest,
      chronicleRecorder,
      liveTranscriptionStatus,
      topBarTranscriptionStatus,
      recordingNoticeStatus,
      showChronistHealthBanner,
      chronistHealthBannerVariant,
      showChronistNotRecordingReminder,
      showJitsiChronistReminder,
    },
    ui: {
      inventoryCharacter,
      setInventoryCharacter,
      sheetCharacter,
      setSheetCharacter,
      showDnd5eSheet,
      fateGmSettingsOpen,
      setFateGmSettingsOpen,
      leftPanel,
      setLeftPanel,
      topPanel,
      setTopPanel,
      toggleTopPanel,
      closeTopPanel,
      stageRosterOpen,
      setStageRosterOpen,
      stageDeckHandOpen,
      setStageDeckHandOpen,
      isShopBusy,
      isStageManagerOpen,
      setIsStageManagerOpen,
      stageSearch,
      setStageSearch,
      showQuests,
      setShowQuests,
      downtimePlayerDismissed,
      setDowntimePlayerDismissed,
      mainSidePanel,
      toggleMainSidePanel,
      closeMainSidePanel,
      toggleLeftPanel,
      closeLeftPanel,
      isDiceOpen,
      setIsDiceOpen,
      prepTestCharacterId,
      setPrepTestCharacterId,
      isEnding,
      startEndTransition,
      wrapUpOpen,
      setWrapUpOpen,
      stageFactionSearch,
      setStageFactionSearch,
      npcSearchModalOpen,
      setNpcSearchModalOpen,
      beastSearchModalOpen,
      setBeastSearchModalOpen,
      quickRulebookModalOpen,
      setQuickRulebookModalOpen,
      creatureStates,
      setCreatureStates,
      beastLootCreatureId,
      setBeastLootCreatureId,
      stageDropHighlight,
      setStageDropHighlight,
      stagePortrait,
      setStagePortrait,
      npcReactions,
      npcReputationScores,
      rollingInitiativeId,
      lightningPulseKey,
      locationDraft,
      setLocationDraft,
      temperatureDraft,
      setTemperatureDraft,
      temperatureValue,
      partyTrayMode,
      setPartyTrayMode,
      weatherCondition,
    },
    battlemap: {
      sessionBattlemaps,
      setSessionWorldMapLinks,
      availableWorldMaps,
      sessionWorldMapLinks,
      battlemapTokens,
      setBattlemapTokens,
      battlemapFogShapes,
      setBattlemapFogShapes,
      battlemapEffectTemplates,
      setBattlemapEffectTemplates,
      battlemapMarkers,
      setBattlemapMarkers,
      battlemapTraps,
      setBattlemapTraps,
      fogTool,
      setFogTool,
      effectTool,
      setEffectTool,
      markerTool,
      setMarkerTool,
      trapTool,
      setTrapTool,
      selectedFogShapeId,
      setSelectedFogShapeId,
      selectedEffectTemplateId,
      setSelectedEffectTemplateId,
      selectedMarkerId,
      setSelectedMarkerId,
      selectedTrapId,
      setSelectedTrapId,
      trapWizardCell,
      setTrapWizardCell,
      trapTriggerEvent,
      setTrapTriggerEvent,
      tokenPlacement,
      setTokenPlacement,
      gmTokenPlacement,
      setGmTokenPlacement,
      gmMoveTokenId,
      setGmMoveTokenId,
      selectedBattlemapTokenId,
      setSelectedBattlemapTokenId,
      selectedBattlemapPropId,
      setSelectedBattlemapPropId,
      tokenRadial,
      setTokenRadial,
      activeBattlemapId,
      activeWorldMapId,
      activeBattlemap,
      battlemapActive,
      notifyBattlemapTokensChanged,
      notifyBattlemapFogChanged,
      notifyBattlemapEffectChanged,
      startCharacterTokenPlacement,
      handleBattlemapCellClick,
      handleBattlemapTokenMove,
      handleFogShapeDelete,
      handleEffectTemplateDelete,
      handleMarkerDelete,
      handleFogClearAll,
      handleEffectClearAll,
      handleMarkerClearAll,
      handleTrapDelete,
      handleTrapClearAll,
      handleBattlemapPropDrop,
      handleBattlemapPropResize,
      visibleBattlemapTokens,
      visibleBattlemapProps,
      battlemapTokenHpByRef,
      characterDisplayUrlById,
      characterConditionsById,
    },
    preload,
    showLoadingScreen,
    derived: {
      dayPhase,
      canEditJournal,
      systemLogs,
      combatStartFxActive,
      combatStartFxKey,
      dismissCombatStartFx,
      handRaises,
      urgentHandRaise,
      physicallyPresentIdSet,
      dummyPlayerCountLive,
      displayPartyCharacters,
      playerColorByCharacterId,
      playerColorByUserId,
      weatherVisual,
      currentPlayerCharacter,
      activityCharacter,
      activeNpcIds,
      sortedActiveNpcs,
      activeCreatures,
      gmBeastSearchRows,
      gmNpcSearchRows,
      activeCreatureIds,
      activeSceneMedia,
      activeFactionIds,
      activeFactions,
      stageRosterPreview,
      stageHasDeckContent,
      filteredNpcsForStageManager,
      filteredFactionsForStageManager,
      inHandNpcs,
      inHandFactions,
      inHandScenes,
      showGmDeckHand,
      battlemapTrayNpcs,
      battlemapTrayCreatures,
      battlemapTrayScenes,
      stagePrepHref,
    },
    combat: {
      setCombatParticipants,
      sortedCombatParticipants,
      combatStarted,
      activeCombatParticipant,
      activeTurnHighlight,
      combatParticipantNames,
      combatParticipantNpcIds,
      seedCombatParticipantsFromBattlemap,
      dragCombatToken,
      addCombatToken,
      battlemapTokenToCombatPayload,
      handleRollInitiative,
      beginCombatEncounter,
      endCombatEncounter,
      nextCombatTurn,
      prevCombatTurn,
      handlePlayerEndTurn,
    },
    stageActions: {
      revealNpcOnCampaignIfNeeded,
      placeOnStage,
      removeFromStage,
      handleNpcReaction,
      toggleShopForNpc,
      assignMerchantAndOpenShop,
      assignScribe,
      commitTemperatureValue,
    },
    location: { changeSessionLocation, resetBackgroundToLocationDefault },
    updateLiveState,
    writeSystemLog,
    presentUserIds,
  } = useLiveSessionBoardContext();
  return (
    <>
      <LiveSessionModals
        isGM={isGM}
        sessionId={sessionId}
        campaignId={campaignId}
        showLoadingScreen={showLoadingScreen}
        combatStartFxActive={combatStartFxActive}
        combatStartFxKey={combatStartFxKey}
        dismissCombatStartFx={dismissCombatStartFx}
        npcSearchModalOpen={npcSearchModalOpen}
        setNpcSearchModalOpen={setNpcSearchModalOpen}
        gmNpcSearchRows={gmNpcSearchRows}
        stageDeckNpcIds={stageDeckNpcIds}
        currentLocationLoreId={liveState?.current_location_lore_id ?? null}
        activeNpcIds={activeNpcIds}
        onPlaceNpc={(id) => placeOnStage("npc", id)}
        beastSearchModalOpen={beastSearchModalOpen}
        setBeastSearchModalOpen={setBeastSearchModalOpen}
        quickRulebookModalOpen={quickRulebookModalOpen}
        setQuickRulebookModalOpen={setQuickRulebookModalOpen}
        gmBeastSearchRows={gmBeastSearchRows}
        stageDeckCreatureIds={stageDeckCreatureIds}
        activeCreatureIds={activeCreatureIds}
        onPlaceCreature={(id) => placeOnStage("creature", id)}
        beastLootCreatureId={beastLootCreatureId}
        setBeastLootCreatureId={setBeastLootCreatureId}
        allCampaignCreatures={allCampaignCreatures}
        writeSystemLog={writeSystemLog}
        inventoryCharacter={inventoryCharacter}
        setInventoryCharacter={setInventoryCharacter}
        partyCharacters={partyCharacters}
        refreshLiveState={refreshLiveState}
        router={router}
        sheetCharacter={sheetCharacter}
        setSheetCharacter={setSheetCharacter}
        showDnd5eSheet={showDnd5eSheet}
        liveState={liveState}
        trapWizardCell={trapWizardCell}
        setTrapWizardCell={setTrapWizardCell}
        setTrapTool={setTrapTool}
        activeBattlemapId={activeBattlemapId}
        currentLocationName={liveState?.current_location}
        setSelectedTrapId={setSelectedTrapId}
        setBattlemapTraps={setBattlemapTraps}
        trapTriggerEvent={trapTriggerEvent}
        setTrapTriggerEvent={setTrapTriggerEvent}
        wrapUpOpen={wrapUpOpen}
        setWrapUpOpen={setWrapUpOpen}
        chronicleRecorder={chronicleRecorder}
        liveTranscriptionStatus={liveTranscriptionStatus}
        startEndTransition={startEndTransition}
      />

      <DiceRollOverlay
        logs={systemLogs as import("@/src/lib/actions/session-activity-actions").SessionActivityEntry[]}
      />

      <LiveSessionTokenRadialMenuHost
        tokenRadial={tokenRadial}
        setTokenRadial={setTokenRadial}
        isGM={isGM}
        battlemapTokenHpByRef={battlemapTokenHpByRef}
        setGmMoveTokenId={setGmMoveTokenId}
        setGmTokenPlacement={setGmTokenPlacement}
        setTokenPlacement={setTokenPlacement}
        partyCharacters={partyCharacters}
        startCharacterTokenPlacement={startCharacterTokenPlacement}
        startTransition={startTransition}
        sessionId={sessionId}
        setBattlemapTokens={setBattlemapTokens}
        notifyBattlemapTokensChanged={notifyBattlemapTokensChanged}
        setSelectedBattlemapTokenId={setSelectedBattlemapTokenId}
        liveState={liveState}
        battlemapTokenToCombatPayload={battlemapTokenToCombatPayload}
        combatParticipantNames={combatParticipantNames}
        combatParticipantNpcIds={combatParticipantNpcIds}
        addCombatToken={addCombatToken}
      />
    </>
  );
}

