/**
 * LiveSessionBoardDockPanelsLayer — Left dock and right side panels.
 */
"use client";

import { LiveSessionLeftDockSession } from "./LiveSessionLeftDockSession";
import { LiveSessionSidePanelsHost } from "./LiveSessionSidePanelsHost";
import { useLiveSessionBoardContext } from "./LiveSessionBoardContext";

export function LiveSessionBoardDockPanelsLayer() {
  const {
    props: {
      sessionId,
      campaignId,
      worldId,
      sessionStatus,
      actualUserIsGM,
      isGuest,
      guestDisplayName,
      guestSlotIndex,
      forcePlayerView,
      userId,
      partyCharacters,
      allCampaignNpcs,
      allCampaignCreatures,
      stageDeckNpcIds,
      stageDeckCreatureIds,
      allSceneMedia,
      activeQuests,
      loreLocationOptions,
      sessionLocationLoreReadable,
      campaignShops,
      guestJoinUrl,
    },
    router,
    isGM,
    isUpdating,
    startTransition,
    bootstrap: {
      liveState,
      setLiveState,
      liveStateRef,
      isLiveStateInitializing,
      liveStateLoadError,
      backgroundUrl,
      resolveLiveStateBase,
      refreshLiveState,
    },
    chronicle: {
      activeTranscriptionMode,
      setActiveTranscriptionMode,
      chronistPanelOpen,
      setChronistPanelOpen,
      chronistStartFlowRef,
      chronistStopFlowRef,
      chronistSettingsFlowRef,
      recordingNoticeModalOpen,
      dismissChronistRecordingReminder,
      dismissJitsiChronistReminder,
      dismissRecordingNotice,
      isPrepMode,
      chronistTableMode,
      prepMicTest,
      chronicleRecorder,
      liveTranscriptionStatus,
      topBarTranscriptionStatus,
      recordingNoticeStatus,
      showChronistHealthBanner,
      chronistHealthBannerVariant,
      showChronistNotRecordingReminder,
      showJitsiChronistReminder,
    },
    ui: {
      inventoryCharacter,
      setInventoryCharacter,
      sheetCharacter,
      setSheetCharacter,
      showDnd5eSheet,
      fateGmSettingsOpen,
      setFateGmSettingsOpen,
      leftPanel,
      setLeftPanel,
      topPanel,
      setTopPanel,
      toggleTopPanel,
      closeTopPanel,
      stageRosterOpen,
      setStageRosterOpen,
      stageDeckHandOpen,
      setStageDeckHandOpen,
      isShopBusy,
      isStageManagerOpen,
      setIsStageManagerOpen,
      stageSearch,
      setStageSearch,
      showQuests,
      setShowQuests,
      downtimePlayerDismissed,
      setDowntimePlayerDismissed,
      mainSidePanel,
      toggleMainSidePanel,
      closeMainSidePanel,
      toggleLeftPanel,
      closeLeftPanel,
      isDiceOpen,
      setIsDiceOpen,
      prepTestCharacterId,
      setPrepTestCharacterId,
      isEnding,
      startEndTransition,
      wrapUpOpen,
      setWrapUpOpen,
      stageFactionSearch,
      setStageFactionSearch,
      npcSearchModalOpen,
      setNpcSearchModalOpen,
      beastSearchModalOpen,
      setBeastSearchModalOpen,
      setQuickRulebookModalOpen,
      creatureStates,
      setCreatureStates,
      beastLootCreatureId,
      setBeastLootCreatureId,
      stageDropHighlight,
      setStageDropHighlight,
      stagePortrait,
      setStagePortrait,
      npcReactions,
      npcReputationScores,
      rollingInitiativeId,
      lightningPulseKey,
      locationDraft,
      setLocationDraft,
      temperatureDraft,
      setTemperatureDraft,
      temperatureValue,
      partyTrayMode,
      setPartyTrayMode,
      weatherCondition,
    },
    battlemap: {
      sessionBattlemaps,
      setSessionWorldMapLinks,
      availableWorldMaps,
      sessionWorldMapLinks,
      battlemapTokens,
      setBattlemapTokens,
      battlemapFogShapes,
      setBattlemapFogShapes,
      battlemapEffectTemplates,
      setBattlemapEffectTemplates,
      battlemapMarkers,
      setBattlemapMarkers,
      battlemapTraps,
      setBattlemapTraps,
      battlemapContainers,
      containerTool,
      setContainerTool,
      selectedContainerId,
      setSelectedContainerId,
      fogTool,
      setFogTool,
      effectTool,
      setEffectTool,
      markerTool,
      setMarkerTool,
      trapTool,
      setTrapTool,
      drawTool,
      setDrawTool,
      drawColor,
      setDrawColor,
      drawWidth,
      setDrawWidth,
      drawStrokeCount,
      setDrawStrokeCount,
      poiTool,
      setPoiTool,
      selectedPoiId,
      setSelectedPoiId,
      worldMapPoiCount,
      setWorldMapPoiCount,
      worldMapPoiClearReq,
      setWorldMapPoiClearReq,
      worldMapPoiDeleteReq,
      setWorldMapPoiDeleteReq,
      worldMapFogCount,
      setWorldMapFogCount,
      worldMapEffectCount,
      setWorldMapEffectCount,
      worldMapMarkerCount,
      setWorldMapMarkerCount,
      worldMapFogClearReq,
      setWorldMapFogClearReq,
      worldMapEffectClearReq,
      setWorldMapEffectClearReq,
      worldMapMarkerClearReq,
      setWorldMapMarkerClearReq,
      drawUndoReq,
      setDrawUndoReq,
      drawClearReq,
      setDrawClearReq,
      selectedFogShapeId,
      setSelectedFogShapeId,
      selectedEffectTemplateId,
      setSelectedEffectTemplateId,
      selectedMarkerId,
      setSelectedMarkerId,
      selectedTrapId,
      setSelectedTrapId,
      trapWizardCell,
      setTrapWizardCell,
      trapTriggerEvent,
      setTrapTriggerEvent,
      tokenPlacement,
      setTokenPlacement,
      gmTokenPlacement,
      setGmTokenPlacement,
      gmMoveTokenId,
      setGmMoveTokenId,
      selectedBattlemapTokenId,
      setSelectedBattlemapTokenId,
      selectedBattlemapPropId,
      setSelectedBattlemapPropId,
      tokenRadial,
      setTokenRadial,
      activeBattlemapId,
      activeWorldMapId,
      activeBattlemap,
      battlemapActive,
      mapToolsActive,
      worldMapActive,
      notifyBattlemapTokensChanged,
      notifyBattlemapFogChanged,
      notifyBattlemapEffectChanged,
      startCharacterTokenPlacement,
      handleBattlemapCellClick,
      handleBattlemapTokenMove,
      handleFogShapeDelete,
      handleEffectTemplateDelete,
      handleMarkerDelete,
      handleFogClearAll,
      handleEffectClearAll,
      handleMarkerClearAll,
      handleTrapDelete,
      handleTrapClearAll,
      handleContainerDelete,
      handleContainerClearAll,
      handleBattlemapPropDrop,
      handleBattlemapPropResize,
      visibleBattlemapTokens,
      visibleBattlemapProps,
      battlemapTokenHpByRef,
      characterDisplayUrlById,
      characterConditionsById,
    },
    preload,
    showLoadingScreen,
    derived: {
      dayPhase,
      canEditJournal,
      systemLogs,
      combatStartFxActive,
      combatStartFxKey,
      dismissCombatStartFx,
      handRaises,
      urgentHandRaise,
      physicallyPresentIdSet,
      dummyPlayerCountLive,
      displayPartyCharacters,
      playerColorByCharacterId,
      playerColorByUserId,
      weatherVisual,
      currentPlayerCharacter,
      activityCharacter,
      activeNpcIds,
      sortedActiveNpcs,
      activeCreatures,
      gmBeastSearchRows,
      gmNpcSearchRows,
      activeCreatureIds,
      activeSceneMedia,
      activeFactionIds,
      activeFactions,
      stageRosterPreview,
      stageHasDeckContent,
      filteredNpcsForStageManager,
      filteredFactionsForStageManager,
      inHandNpcs,
      inHandFactions,
      inHandScenes,
      showGmDeckHand,
      battlemapTrayNpcs,
      battlemapTrayCreatures,
      battlemapTrayScenes,
      stagePrepHref,
    },
    combat: {
      setCombatParticipants,
      sortedCombatParticipants,
      combatStarted,
      activeCombatParticipant,
      activeTurnHighlight,
      combatParticipantNames,
      combatParticipantNpcIds,
      seedCombatParticipantsFromBattlemap,
      dragCombatToken,
      addCombatToken,
      battlemapTokenToCombatPayload,
      handleRollInitiative,
      beginCombatEncounter,
      endCombatEncounter,
      nextCombatTurn,
      prevCombatTurn,
      handlePlayerEndTurn,
    },
    stageActions: {
      revealNpcOnCampaignIfNeeded,
      placeOnStage,
      removeFromStage,
      handleNpcReaction,
      toggleShopForNpc,
      assignMerchantAndOpenShop,
      assignScribe,
      commitTemperatureValue,
    },
    location: { changeSessionLocation, resetBackgroundToLocationDefault },
    updateLiveState,
    writeSystemLog,
    presentUserIds,
  } = useLiveSessionBoardContext();
  return (
    <>
      <LiveSessionLeftDockSession
        leftPanel={leftPanel}
        toggleLeftPanel={toggleLeftPanel}
        closeLeftPanel={closeLeftPanel}
        isGM={isGM}
        forcePlayerView={forcePlayerView}
        isGuest={isGuest}
        isDiceOpen={isDiceOpen}
        setIsDiceOpen={setIsDiceOpen}
        setLeftPanel={setLeftPanel}
        setTopPanel={setTopPanel}
        partyTrayMode={partyTrayMode}
        setPartyTrayMode={setPartyTrayMode}
        sessionId={sessionId}
        campaignId={campaignId}
        activityCharacter={activityCharacter}
        userId={userId}
        isPrepMode={isPrepMode}
        partyCharacters={partyCharacters}
        currentPlayerCharacter={currentPlayerCharacter}
        prepTestCharacterId={prepTestCharacterId}
        setPrepTestCharacterId={setPrepTestCharacterId}
        setLiveState={setLiveState}
        liveStateRef={liveStateRef}
        activityLogs={liveState?.system_logs ?? []}
        weatherVisual={weatherVisual}
        dayPhase={dayPhase}
        temperatureValue={temperatureValue}
        chronicleRecorder={chronicleRecorder}
        physicallyPresentIdSet={physicallyPresentIdSet}
        dummyPlayerCountLive={dummyPlayerCountLive}
        battlemapActive={battlemapActive}
        mapToolsActive={mapToolsActive}
        worldMapActive={worldMapActive}
        fogTool={fogTool}
        setFogTool={setFogTool}
        selectedFogShapeId={selectedFogShapeId}
        setSelectedFogShapeId={setSelectedFogShapeId}
        effectTool={effectTool}
        setEffectTool={setEffectTool}
        selectedEffectTemplateId={selectedEffectTemplateId}
        setSelectedEffectTemplateId={setSelectedEffectTemplateId}
        markerTool={markerTool}
        setMarkerTool={setMarkerTool}
        selectedMarkerId={selectedMarkerId}
        setSelectedMarkerId={setSelectedMarkerId}
        trapTool={trapTool}
        setTrapTool={setTrapTool}
        selectedTrapId={selectedTrapId}
        setSelectedTrapId={setSelectedTrapId}
        containerTool={containerTool}
        setContainerTool={setContainerTool}
        selectedContainerId={selectedContainerId}
        setSelectedContainerId={setSelectedContainerId}
        drawTool={drawTool}
        setDrawTool={setDrawTool}
        drawColor={drawColor}
        setDrawColor={setDrawColor}
        drawWidth={drawWidth}
        setDrawWidth={setDrawWidth}
        drawStrokeCount={drawStrokeCount}
        onDrawUndo={() => setDrawUndoReq((n) => n + 1)}
        onDrawClearAll={() => setDrawClearReq((n) => n + 1)}
        poiTool={poiTool}
        setPoiTool={setPoiTool}
        selectedPoiId={selectedPoiId}
        setSelectedPoiId={setSelectedPoiId}
        worldMapPoiCount={worldMapPoiCount}
        onWorldMapPoiClearAll={() => setWorldMapPoiClearReq((n) => n + 1)}
        onWorldMapPoiDelete={() => setWorldMapPoiDeleteReq((n) => n + 1)}
        worldMapFogCount={worldMapFogCount}
        worldMapEffectCount={worldMapEffectCount}
        worldMapMarkerCount={worldMapMarkerCount}
        onWorldMapFogClearAll={() => setWorldMapFogClearReq((n) => n + 1)}
        onWorldMapEffectClearAll={() => setWorldMapEffectClearReq((n) => n + 1)}
        onWorldMapMarkerClearAll={() => setWorldMapMarkerClearReq((n) => n + 1)}
        setTokenPlacement={setTokenPlacement}
        setGmTokenPlacement={setGmTokenPlacement}
        setGmMoveTokenId={setGmMoveTokenId}
        setSelectedBattlemapTokenId={setSelectedBattlemapTokenId}
        setSelectedBattlemapPropId={setSelectedBattlemapPropId}
        battlemapMarkers={battlemapMarkers}
        handleMarkerDelete={handleMarkerDelete}
        handleMarkerClearAll={handleMarkerClearAll}
        battlemapTraps={battlemapTraps}
        battlemapContainers={battlemapContainers}
        handleTrapDelete={handleTrapDelete}
        handleTrapClearAll={handleTrapClearAll}
        handleContainerDelete={handleContainerDelete}
        handleContainerClearAll={handleContainerClearAll}
        battlemapEffectTemplates={battlemapEffectTemplates}
        handleEffectTemplateDelete={handleEffectTemplateDelete}
        handleEffectClearAll={handleEffectClearAll}
        battlemapFogShapes={battlemapFogShapes}
        handleFogShapeDelete={handleFogShapeDelete}
        handleFogClearAll={handleFogClearAll}
        liveState={liveState}
        temperatureDraft={temperatureDraft}
        setTemperatureDraft={setTemperatureDraft}
        commitTemperatureValue={commitTemperatureValue}
        updateLiveState={updateLiveState}
        writeSystemLog={writeSystemLog}
        sessionStatus={sessionStatus}
        chronistTableMode={chronistTableMode}
        worldId={worldId}
        activeTranscriptionMode={activeTranscriptionMode}
        setActiveTranscriptionMode={setActiveTranscriptionMode}
        prepMicTest={prepMicTest}
        chronistPanelOpen={chronistPanelOpen}
        setChronistPanelOpen={setChronistPanelOpen}
        chronistStartFlowRef={chronistStartFlowRef}
        chronistStopFlowRef={chronistStopFlowRef}
        chronistSettingsFlowRef={chronistSettingsFlowRef}
        allCampaignNpcs={allCampaignNpcs}
        isUpdating={isUpdating}
        showDnd5eSheet={showDnd5eSheet}
        setQuickRulebookModalOpen={setQuickRulebookModalOpen}
      />

      <LiveSessionSidePanelsHost
        isGuest={isGuest}
        sessionId={sessionId}
        campaignId={campaignId}
        isGM={isGM}
        forcePlayerView={forcePlayerView}
        isPrepMode={isPrepMode}
        mainSidePanel={mainSidePanel}
        toggleMainSidePanel={toggleMainSidePanel}
        closeMainSidePanel={closeMainSidePanel}
        handRaises={handRaises}
        liveState={liveState}
        systemLogs={systemLogs}
        activityCharacter={activityCharacter}
        partyCharacters={partyCharacters}
        currentPlayerCharacter={currentPlayerCharacter}
        prepTestCharacterId={prepTestCharacterId}
        setPrepTestCharacterId={setPrepTestCharacterId}
        setLiveState={setLiveState}
        liveStateRef={liveStateRef}
        userId={userId}
        playerColorByCharacterId={playerColorByCharacterId}
        refreshLiveState={refreshLiveState}
        canEditJournal={canEditJournal}
        allSceneMedia={allSceneMedia}
        placeOnStage={placeOnStage}
        removeFromStage={removeFromStage}
        sessionBattlemaps={sessionBattlemaps}
        activeBattlemapId={activeBattlemapId}
        setSelectedBattlemapTokenId={setSelectedBattlemapTokenId}
        setSelectedBattlemapPropId={setSelectedBattlemapPropId}
        availableWorldMaps={availableWorldMaps}
        sessionWorldMapLinks={sessionWorldMapLinks}
        setSessionWorldMapLinks={setSessionWorldMapLinks}
        battlemapActive={battlemapActive}
        displayPartyCharacters={displayPartyCharacters}
        battlemapTrayNpcs={battlemapTrayNpcs}
        battlemapTrayCreatures={battlemapTrayCreatures}
        startCharacterTokenPlacement={startCharacterTokenPlacement}
        setGmTokenPlacement={setGmTokenPlacement}
        setGmMoveTokenId={setGmMoveTokenId}
        setTokenPlacement={setTokenPlacement}
        router={router}
        updateLiveState={updateLiveState}
        writeSystemLog={writeSystemLog}
        playerColorByUserId={playerColorByUserId}
        urgentHandRaise={urgentHandRaise}
        isUpdating={isUpdating}
        startTransition={startTransition}
      />

    </>
  );
}

